sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx
  
haxe:
  - "3.4.0"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - haxelib git tink_unittest https://github.com/kevinresol/tink_unittest
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix node -lib tink_unittest
  - haxelib run travix cs -lib tink_unittest
  - haxelib run travix java -lib tink_unittest
  - haxelib run travix python -lib tink_unittest
  - haxelib run travix php -lib tink_unittest
  - haxelib run travix cpp -lib tink_unittest
