sudo: required
dist: trusty

stages:
  - test
  - deploy

language: node_js
node_js: 8

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=latest
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download

script:
  - lix run travix node
  # - lix run travix cs # type paramters...
  # - lix run travix java # type paramters...
  # - lix run travix python # ???
  - lix run travix php
  - lix run travix cpp
  # - lix run travix lua 
  - lix run travix neko
  - lix run travix interp

  
jobs:
  include:
    # - stage: test # should uncomment this when there is no matrix above (e.g. only one os, one env, etc)
    - stage: deploy
      os: linux
      script: skip
      env:
        secure: ZHfmyegShsvV61rIuLfu9YyhXULmwR7ax7+vhWt57dtStppbetaIFtAz+iJwXDHdReH8Z+1tPIXNrSjz0pEn+dp+3ov+TwJJXP0vPeEOvyoMI3pcNKAT3IP0nGBUf0xoOh/9g9RBTPgS5nH7wVNu33uk7Eh2HW/TfMYVlGxiuvJ74fhsA2UgD9PWIeTnC9LW7AxdAzhXz26a70fHj30bHAG8jKJZcLYSCl7Vb7+BkYx+WUonpt9lXeOz34QQTMlf/k2EVRU5r97Qnv8F9x+qCS/zI/H7qZp2+VrbfdnUbBfHgOgRpiow0sSj9Z3I/NsvO7v5nAnASSnZb4FmFty9iy8AetleUv8q27VUqlolzSQ83SipjjG4VwbB4ZVqfYb2uzWBmB3TZUyHSBvp9JWc4etd5EhaNWvQ4FVkC8kKHECPBfCarA36XS1DHpj+6rVj3iNnQkfKXFCCv1AhP318sSByETZIMEhTU8h3zXY5D5SL7A8nIMDCyPSREnhwt7J0YA/tuCO7/EZ67lDKixWyoGWZs3pj5yyAhiXd1bfJ2Cdv2bYRFA94BjGzIEfVepdJo/Toda8Ort8VadsGJSI8DEOrd2JcdlbRBCiA/+Tu5Jf3knsFo/3ug4rvTK7Vg/lo9YwYpneTjPhLUx6SLpUwBD1wnSoum84rf6wh6B5J7x4=
      after_success:
        - lix run travix install
        - lix run travix release
